repos:
- repo: local
  hooks:
    - id: encrypt files
      name: encrypt files
      entry: .pre-commit-sops.sh
      language: script
      pass_filenames: true
      verbose: true
      always_run: true
